# Generated by Django 4.2.23 on 2025-08-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('office', 'Office'), ('retail', 'Retail'), ('other', 'Other')], max_length=20)),
                ('address', models.TextField()),
                ('name', models.TextField()),
                ('amenities', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
